### ISSUE TITLE
group 分组没反应，官方那个链接可以

### ISSUE THREAD

**Issue by wlrsx** [cwxiaos/bark-worker#10]
看了代码找不出问题所在。。。

**Comment by cwxiaos** [comment]
分组功能正常，可以尝试重启设备或检查分组名。

![image](https://github.com/user-attachments/assets/bb6cf34b-f005-46e7-b601-344b998d3640)

**Comment by cwxiaos** [comment]
Group在我自己的设备上（iOS 18.2)需要一定数量的消息才能触发, 当消息数量较少时依然是展开的列表.

**Comment by qwe7002** [comment]
> 看了代码找不出问题所在。。。

我把这个问题修了，您可以试试新的版本。
