### ISSUE TITLE
使用教程配置后无法使用自定义域

### ISSUE THREAD

**Issue by Emtier** [cwxiaos/bark-worker#2]
现在使用workers.dev是可以正常推送，但是国内需要开VPN。绑定了自己的域名，首页可以打开，也可以/ping。但是把/key/test，无法访问，一访问就会下载一个文件test的文件

**Comment by cwxiaos** [comment]
已修复相关问题，请尝试更新代码并重试

如果仍然存在问题，请检查以下可能的情况：

1.检查浏览器及相关插件，浏览器可能将内容自动保存为文件，如果问题任然存在，请尝试更换浏览器或使用curl等工具发起请求
2.清理浏览器缓存，并打开Cloudflare的开发模式，打开Websites -> [绑定的域名] -> Development Mode

如果问题任然存在，请在Workers & Pages -> Overview -> [创建的Worker] -> Logs 中打开日志记录，此后发起请求，将存在问题的日志发送到此issue中。

**Comment by Emtier** [comment]
> 已修复相关问题，请尝试更新代码并重试
> 
> 如果仍然存在问题，请检查以下可能的情况：
> 
> 1.检查浏览器及相关插件，浏览器可能将内容自动保存为文件，如果问题任然存在，请尝试更换浏览器或使用curl等工具发起请求 2.清理浏览器缓存，并打开Cloudflare的开发模式，打开Websites -> [绑定的域名] -> Development Mode
> 
> 如果问题任然存在，请在Workers & Pages -> Overview -> [创建的Worker] -> Logs 中打开日志记录，此后发起请求，将存在问题的日志发送到此issue中。

问题依旧，curl之后无显示
Exception | GET | https://api.ilisuo.cn/REDACTED/test | 2024/6/7 14:04:14

{
  "outcome": "exception",
  "scriptVersion": {
    "id": "ce413841-2c5f-4e43-bf10-d9f61c293278"
  },
  "scriptName": "bark-server",
  "diagnosticsChannelEvents": [],
  "exceptions": [
    {
      "stack": "    at JSON.parse (<anonymous>)\n    at Handler.push (worker.js:305:53)\n    at async Object.fetch (worker.js:3:16)",
      "name": "SyntaxError",
      "message": "Unexpected token 'e', \"error code: 520\" is not valid JSON",
      "timestamp": 1717740254723
    }
  ],
  "logs": [],
  "eventTimestamp": 1717740254125,
  "event": {
    "request": {
      "url": "https://api.ilisuo.cn/REDACTED/test",
      "method": "GET",
      "headers": {
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "accept-encoding": "gzip, br",
        "accept-language": "zh-CN,zh-Hans;q=0.9",
        "cf-connecting-ip": "106.89.214.207",
        "cf-ipcountry": "CN",
        "cf-ray": "88fe71877a4760f3",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "host": "api.ilisuo.cn",
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "none",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
        "x-forwarded-proto": "https",
        "x-real-ip": "106.89.214.207"
      },
      "cf": {
        "clientTcpRtt": 221,
        "longitude": "106.55770",
        "latitude": "29.56890",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 4134,
        "clientAcceptEncoding": "gzip, deflate, br",
        "country": "CN",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "verifiedBotCategory": "",
        "tlsExportedAuthenticator": {
          "clientFinished": "e4c441d34cee0cba594b2aade894e104b3599922db27964560c967c99c8e56bd",
          "clientHandshake": "bd9228d28151d653b2e4920bbc8120c22e9e6ca8b7175a97d92a05a574b1aa3f",
          "serverHandshake": "a1293c2821871ea5365bc70344d224b8d4a7a27e165d2050a3e2139f2fd2b451",
          "serverFinished": "b2f74bfae2c8a4ae2d35e3f0c01ac05735da7ee96347859fceabc7c47b10b4ec"
        },
        "tlsVersion": "TLSv1.3",
        "colo": "LHR",
        "timezone": "Asia/Shanghai",
        "tlsClientHelloLength": "508",
        "edgeRequestKeepAliveStatus": 1,
        "requestPriority": "weight=255;exclusive=0;group=0;group-weight=0",
        "tlsClientExtensionsSha1": "4uRWtPNW4kQk3QFQqla/ATjsoBI=",
        "region": "Chongqing",
        "city": "Chongqing",
        "regionCode": "CQ",
        "asOrganization": "China Telecom",
        "tlsClientRandom": "ci+VyJsRQyP7/4dx2lYnsEwoMUvJ+1sXiG1GIuJX9T4=",
        "httpProtocol": "HTTP/2",
        "botManagement": {
          "corporateProxy": false,
          "verifiedBot": false,
          "jsDetection": {
            "passed": false
          },
          "staticResource": false,
          "detectionIds": {},
          "score": 99
        }
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 0
}

**Comment by Emtier** [comment]
> 已修复相关问题，请尝试更新代码并重试
> 
> 如果仍然存在问题，请检查以下可能的情况：
> 
> 1.检查浏览器及相关插件，浏览器可能将内容自动保存为文件，如果问题任然存在，请尝试更换浏览器或使用curl等工具发起请求 2.清理浏览器缓存，并打开Cloudflare的开发模式，打开Websites -> [绑定的域名] -> Development Mode
> 
> 如果问题任然存在，请在Workers & Pages -> Overview -> [创建的Worker] -> Logs 中打开日志记录，此后发起请求，将存在问题的日志发送到此issue中。

使用workers.dev :
Ok | GET | https://bark-server.ilisuo.workers.dev/REDACTED/ddns | 2024/6/7 14:05:47
{
  "outcome": "ok",
  "scriptVersion": {
    "id": "ce413841-2c5f-4e43-bf10-d9f61c293278"
  },
  "scriptName": "bark-server",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [],
  "eventTimestamp": 1717740347614,
  "event": {
    "request": {
      "url": "https://bark-server.ilisuo.workers.dev/REDACTED/ddns",
      "method": "GET",
      "headers": {
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "accept-encoding": "gzip, br",
        "accept-language": "zh-CN,zh-Hans;q=0.9",
        "cf-connecting-ip": "46.3.240.212",
        "cf-ipcountry": "HK",
        "cf-ray": "88fe73d44ebf07ad",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "host": "bark-server.ilisuo.workers.dev",
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "none",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
        "x-forwarded-proto": "https",
        "x-real-ip": "46.3.240.212"
      },
      "cf": {
        "clientTcpRtt": 1,
        "longitude": "114.16570",
        "httpProtocol": "HTTP/2",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 38136,
        "clientAcceptEncoding": "gzip, deflate, br",
        "country": "HK",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsExportedAuthenticator": {
          "clientFinished": "47b6ba156b571dfbc95456526fd7cea772830408ea4e75818f6441f0729f18ed",
          "clientHandshake": "705fea9812649dd1ac33d10bb0a94a65327162ca106d4dab2f57d2a9c6f2c1ee",
          "serverHandshake": "b1da2cafc2a203ac94c2e51586b505d79b1f72bc902b62bd34962093e461f97f",
          "serverFinished": "93885acae4b5b3818a1da0dc1408c7fed99b2c5e0c524bdea2f5cc9adacbccfe"
        },
        "tlsVersion": "TLSv1.3",
        "colo": "HKG",
        "timezone": "Asia/Hong_Kong",
        "verifiedBotCategory": "",
        "edgeRequestKeepAliveStatus": 1,
        "tlsClientRandom": "wwftGrGqhhg2115R1R8wXSQY2gCN+Pdngz8G84vDaXA=",
        "tlsClientExtensionsSha1": "fEC5c6n5fdTqtynlcm3moAC6ylY=",
        "tlsClientHelloLength": "508",
        "asOrganization": "Akari Networks Limited",
        "requestPriority": "weight=255;exclusive=0;group=0;group-weight=0",
        "latitude": "22.25780",
        "botManagement": {
          "corporateProxy": false,
          "verifiedBot": false,
          "jsDetection": {
            "passed": false
          },
          "staticResource": false,
          "detectionIds": {},
          "score": 99
        }
      }
    },
    "response": {
      "status": 200
    }
  },
  "id": 3
}

**Comment by cwxiaos** [comment]
已修复相关问题，请更新代码并重试

根据日志信息，该错误是在Cloudflare Worker访问APNs时出现的问题，与Cloudflare和Apple的连接有关。

请尝试重新创建Worker，如果问题仍然存在，请尝试以下方法：

1.借助代理访问自定义域名，若正常，则该问题与Worker IP相关，否则该问题与域名有关
2.更换Worker的IP，可以通过更换Cloudflare账号；开启[创建的Worker] -> Settings -> Placement  -> Smart等方法实现
3.更换网络进行访问，尝试使用数据流量访问

若问题任然存在，请提供日志和Worker的响应信息。

**Comment by Emtier** [comment]
> 已修复相关问题，请更新代码并重试
> 
> 根据日志信息，该错误是在Cloudflare Worker访问APNs时出现的问题，与Cloudflare和Apple的连接有关。
> 
> 请尝试重新创建Worker，如果问题仍然存在，请尝试以下方法：
> 
> 1.借助代理访问自定义域名，若正常，则该问题与Worker IP相关，否则该问题与域名有关 2.更换Worker的IP，可以通过更换Cloudflare账号；开启[创建的Worker] -> Settings -> Placement -> Smart等方法实现 3.更换网络进行访问，尝试使用数据流量访问
> 
> 若问题任然存在，请提供日志和Worker的响应信息。
现在报错，使用代理后报错一样，
{"message":"push failed: error code: 520","code":520,"timestamp":1717747181}

{
  "outcome": "ok",
  "scriptVersion": {
    "id": "ae58bf2e-5213-468c-9752-57ad379d525d"
  },
  "scriptName": "bark-server",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [],
  "eventTimestamp": 1717747249906,
  "event": {
    "request": {
      "url": "https://api.ilisuo.cn/REDACTED/test",
      "method": "GET",
      "headers": {
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "accept-encoding": "gzip, br",
        "accept-language": "zh-CN,zh-Hans;q=0.9",
        "cf-connecting-ip": "106.89.214.207",
        "cf-ipcountry": "CN",
        "cf-ray": "88ff1c542b6b63ce",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "host": "api.ilisuo.cn",
        "priority": "u=0, i",
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "none",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
        "x-forwarded-proto": "https",
        "x-real-ip": "106.89.214.207"
      },
      "cf": {
        "longitude": "106.55770",
        "latitude": "29.56890",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 4134,
        "clientAcceptEncoding": "gzip, deflate, br",
        "country": "CN",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "verifiedBotCategory": "",
        "tlsExportedAuthenticator": {
          "clientFinished": "919133b3b396a5616584a8a790c069d61b2404cc570897b5f223352aad2a6430",
          "clientHandshake": "06edbf560642c0238e896c58198cf0f925473ab3f83b69f81a6453197c878489",
          "serverHandshake": "63152d2082d573d368eb5eb8e59456dfa4ea17cc3b435c00d120701d11bf37ca",
          "serverFinished": "2c43e01aa4d8bb54fb0c87553d1e101dfada1d36300a8b2ba862028a055703c5"
        },
        "tlsVersion": "TLSv1.3",
        "colo": "LHR",
        "timezone": "Asia/Shanghai",
        "tlsClientHelloLength": "253",
        "edgeRequestKeepAliveStatus": 1,
        "requestPriority": "",
        "tlsClientExtensionsSha1": "e8HJFvWd0rcEvoO/y9Qcbx7+KcQ=",
        "region": "Chongqing",
        "city": "Chongqing",
        "regionCode": "CQ",
        "asOrganization": "China Telecom",
        "tlsClientRandom": "ObLKgquNaYB/AVJe8pXZfsgjn2TmSTt/o+Aylg0g8/0=",
        "httpProtocol": "HTTP/3",
        "botManagement": {
          "corporateProxy": false,
          "verifiedBot": false,
          "jsDetection": {
            "passed": false
          },
          "staticResource": false,
          "detectionIds": {},
          "score": 99
        }
      }
    },
    "response": {
      "status": 520
    }
  },
  "id": 0
}

**Comment by cwxiaos** [comment]
该问题成因与Cloudlfare和Apple的连接有关

请尝试以下方法：

1.检查代理，日志中的地区为中国，检查代理的分流规则和代理模式（GLOBAL/RULE）
2.尝试更换网络环境，在手机上使用数据网络访问，相关URL可在Bark APP中查看
3.更换Worker,尝试重新创建worker或切换Cloudflare账号

该问题可能与近期中国大陆的连接阻断有关，若问题仍然存在，尝试等待一段时间并重试

**Comment by 0x032c** [comment]
我这也也出现了一样的问题，一键部署过来注册之后推送就报错 {"code":520,"message":"push failed: error code: 520","timestamp":1759036016}
