### ISSUE TITLE
部分消息无法推送。但使用 https://api.day.app 接口则可以

### ISSUE THREAD

**Issue by gitx6** [cwxiaos/bark-worker#4]
使用 [自动登录和 SSH 自动连接脚本](https://github.com/Sliverkiss/Serv00_Auto_Login/tree/main)。修改为本项目自建的 bark server 可以推送 login.js 的消息，但是无法推送 ssh.py 的消息。改回 https://api.day.app 后，login.js 和 ssh.py 的消息都可以推送

**Comment by cwxiaos** [comment]
经测试，该脚本可以正常推送

![IMG_1588](https://github.com/cwxiaos/bark-worker/assets/21241430/d7f061e0-5a2d-41ea-99e0-15f47144f0cb)

可以通过打印response信息进行具体问题定位

```
        if bark:
            url = f"https://SERVER_ADDRESS/{bark}/Serv00自动登录/账号 {username} SSH连接成功。"
            response = requests.get(url)
            print(response.text)
```

![Screenshot from 2024-06-18 10-30-33](https://github.com/cwxiaos/bark-worker/assets/21241430/a5769c46-0430-4a0f-9a69-9ef09c15f896)

**Comment by gitx6** [comment]
添加 print(response.text) 后的日志记录如下，剩余部分未截取。
<img width="1195" alt="image" src="https://github.com/cwxiaos/bark-worker/assets/24645789/0888983f-8cf1-45e9-beb6-c2a9d282fb4b">

**Comment by cwxiaos** [comment]
触发5秒盾了，建议检查Cloudflare的安全设置

**Comment by gitx6** [comment]
确实被 CF Bot Fight Mode 阻止了。谢谢。
