### ISSUE TITLE
重新部署后保存worker时报错

### ISSUE THREAD

**Issue by lzhsterling** [cwxiaos/bark-worker#6]
API Request Failed: PUT /api/v4/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/workers/services/black-frost-ecb3/environments/production?include_subdomain_availability=true (403)

**Comment by cwxiaos** [comment]
Cloudflare API在昨天（2024-07-26）开始存在故障，引入的安全策略会错误的阻止代码部署及环境变量修改，在Cloudflare修复此问题之前，只能通过wrangler部署（需要手动绑定数据库）。

由于环境变量修改会被Cloudflare API阻止，KV版本不可用。D1版本代码中包含SQL语句，绑定D1数据库需要修改环境变量，因此也不可用。

在此期间，请勿进行任何操作，否则无法重新部署。

**Comment by lzhsterling** [comment]
> Cloudflare API在昨天（2024-07-26）开始存在故障，引入的安全策略会错误的阻止代码部署及环境变量修改，在Cloudflare修复此问题之前，只能通过wrangler部署（需要手动绑定数据库）。
> 
> 由于环境变量修改会被Cloudflare API阻止，KV版本不可用。D1版本代码中包含SQL语句，绑定D1数据库需要修改环境变量，因此也不可用。
> 
> 在此期间，请勿进行任何操作，否则无法重新部署。

大佬，我刚刚直接打包成page，部署成功了，推送也都是正常，强烈强烈pages部署看了一眼请求好像是无限制的，超过10w也没事！
