### ISSUE TITLE
發送英文訊息空格被+替代

### ISSUE THREAD

**Issue by qwe7002** [cwxiaos/bark-worker#8]
![image](https://github.com/user-attachments/assets/beda2873-6014-4b0d-9594-82d9147855fe)

**Comment by qwe7002** [comment]
已經嘗試修復畢竟提交PR

**Comment by cwxiaos** [comment]
The message send to server is not correctly encoded, \\+ is Not a valid encoded URI components. Make sure you message is encoded correctly.
